name: Test

on: [push]

jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Check Current Directory
          run: |
            cd ${{ github.workspace }}
            pwd
            ls
        - name: Execute test
          run: |
            cd ${{ github.workspace }}
            make test
